# Google Gemini Models (Region: us-central1)
gemini.pro=gemini-3-pro-preview
gemini.pro.region=global

# OpenAI Models (Region: us-central1)
openai.gpt.oss.120b=gpt-oss-120b-maas
openai.gpt.oss.120b.region=us-central1
openai.gpt.oss.120b.provider=openai
openai.gpt.oss.120b.openai=true

# Meta Llama Models
# Llama 3.3 models (Region: us-central1)
llama.3_3.70b=llama-3.3-70b-instruct-maas
llama.3_3.70b.region=us-central1
llama.3_3.70b.provider=meta
llama.3_3.70b.openai=true

# Llama 4 models (Region: us-east5)
llama.4.maverick.17b.128e=llama-4-maverick-17b-128e-instruct-maas
llama.4.maverick.17b.128e.region=us-east5
llama.4.maverick.17b.128e.provider=meta
llama.4.maverick.17b.128e.openai=true
llama.4.scout.17b.16e=llama-4-scout-17b-16e-instruct-maas
llama.4.scout.17b.16e.region=us-east5
llama.4.scout.17b.16e.provider=meta
llama.4.scout.17b.16e.openai=true

# DeepSeek Models
# DeepSeek R1 (Region: us-central1)
deepseek.r1.0528=deepseek-r1-0528-maas
deepseek.r1.0528.region=us-central1
deepseek.r1.0528.provider=deepseek-ai
deepseek.r1.0528.openai=true

# Qwen Models
# Qwen3 235B Instruct (Region: us-south1)
qwen3.235b.a22b=qwen3-235b-a22b-instruct-2507-maas
qwen3.235b.a22b.region=us-south1
qwen3.235b.a22b.provider=qwen
qwen3.235b.a22b.openai=true
# Qwen3 Coder (Region: us-south1)
qwen3.coder.480b.a35b=qwen3-coder-480b-a35b-instruct-maas
qwen3.coder.480b.a35b.region=us-south1
qwen3.coder.480b.a35b.provider=qwen
qwen3.coder.480b.a35b.openai=true
# Qwen3 Instruct+Thinking (Region: global)
qwen3.next.80b.a3b=qwen3-next-80b-a3b-instruct-maas
qwen3.next.80b.a3b.region=global
qwen3.next.80b.a3b.provider=qwen
qwen3.next.80b.a3b.openai=true
qwen3.next.80b.a3b.thinking=qwen3-next-80b-a3b-thinking-maas
qwen3.next.80b.a3b.thinking.region=global
qwen3.next.80b.a3b.thinking.provider=qwen
qwen3.next.80b.a3b.thinking.openai=true

# MiniMax Models (Region: global)
minimax.m2=minimax-m2-maas
minimax.m2.region=global
minimax.m2.provider=minimaxai
minimax.m2.openai=true

# Mistral AI Models (Region: europe-west4)
mistral.codestral.2=mistralai/codestral-2@001
mistral.codestral.2.region=europe-west4
mistral.codestral.2.api=rawPredict
mistral.medium.3=mistralai/mistral-medium-3@001
mistral.medium.3.region=europe-west4
mistral.medium.3.api=rawPredict

# Moonshot AI Models (Region: global)
moonshotai.kimi.k2.thinking=kimi-k2-thinking-maas
moonshotai.kimi.k2.thinking.region=global
moonshotai.kimi.k2.thinking.provider=moonshotai
moonshotai.kimi.k2.thinking.openai=true
