gemini.pro=gemini-2.5-pro
llama.maverick=llama-4-maverick-17b-128e-instruct-maas
llama.scout=llama-4-scout-17b-16e-instruct-maas
llama.3_1_405b=llama-3.1-405b-instruct-maas
llama.3_1_70b=llama-3.1-70b-instruct-maas
codestral.2=codestral-22b-instruct-maas
